[package]
name = "generator-utils"
version = "0.0.0"
authors = ["Dodo <kasper199914@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Library for Generator utilities and combinators"

[dependencies]
ergo-pin = {git = "https://github.com/Nemo157/ergo-pin-rs.git"}